name: PvpRoom
version: '0.4-Alpha'
main: PvpRoom.pvpRoom.Main
api-version: '1.19'
authors: [ MrLejen ]
description: This plugin is for creating a room dedicated to fighting between two or more people.
website: https://github.com/mrlejen12/PvpRoom
commands:
  pvproom:
    permission: op
